name: e2e and format tests

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - 'dev/**'
      - '.github/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: node-modules-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm ci

      - name: Run tests
        run: npm test
